// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: RevokeRefreshTokenByToken.sql

package database

import (
	"context"
)

const revokeRefreshTokenByToken = `-- name: RevokeRefreshTokenByToken :exec
UPDATE refresh_tokens SET revoked_at = CURRENT_TIMESTAMP WHERE token = $1
`

func (q *Queries) RevokeRefreshTokenByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokenByToken, token)
	return err
}
